### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by ZeroDevOfficial** [MCMrARM/google_play_downloader#3]
how do I install

**Comment by ghost** [comment]
Just download the binary from the branch( _gh-page_ ) and then just do

> java -jar /path/to/your/playdl.jar
> Email: <email>
> Password: <password>

**Comment by ZeroDevOfficial** [comment]
im don’t know much about Linux so i need better instructions sorry

**Comment by ZeroDevOfficial** [comment]
mr.arm please can you help me i dont know how install

**Comment by ZeroDevOfficial** [comment]
i bought mcpe and i need this to get mcpe on my pc

**Comment by ZeroDevOfficial** [comment]
Please help

**Comment by ZeroDevOfficial** [comment]
How do I install Mr.arm please help I have paid for mcpe but I don't know how to get on Linux
